# Generated by Django 2.1.3 on 2018-11-07 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='status',
        ),
    ]
